[package]
authors = [ "Justin Martin <hello@justinmart.in>" ]
description = "A library to discover, connect and write laser data to Etherdream devices."
edition = "2024"
license = "MIT"
name = "etherdream"
repository = "https://github.com/justinbmartin/etherdream-rs"
version = "0.1.0"

[dependencies]
futures = { version = "0.3" }
tokio = { workspace = true }
tokio-util = { workspace = true, features = [ "codec", "net" ] }

[dev-dependencies]
etherdream-simulator = { path = "../etherdream-simulator" }
tokio = { workspace = true }
