[package]
authors = [ "Justin Martin <hello@justinmart.in>" ]
description = "Etherdream device simulator."
edition = "2024"
license = "MIT"
name = "etherdream-simulator"
repository = "https://github.com/justinbmartin/etherdream-rs"
version = "0.1.0"

[dependencies]
etherdream = { path = "../etherdream" }
tokio = { workspace = true, features = [ "rt-multi-thread" ] }
tokio-util = { workspace = true }